# Testing Libraries: Numpy

In our python journey towards data science we gotta learn how to use shit to plot stuff and do numbers n shit so here we go. 

* NumPy: Numerical Python: [Beginner's Guide](https://numpy.org/doc/stable/user/absolute_beginners.html)

 Contains a variety of mathematical objects (i.e. arrays) and functions to work with them which are very efficient, like max instead of writing oneself a loop to get the fucking number. 

In [15]:
import numpy as np
# Docstring: occurs as the first statement in a module, function, class, or method definition.
# One of the most important objects: arrays
?np.array

Arrays are homogeneous, i.e. only one data type in them against lists, it is more efficient w memory and easier to operate on. 

In [16]:
x = np.array([1, 2, 3, 4, 5, 6,-8])

print(x,type(x))
# Elements are indexed
print(x[1],x[0],x[0:4])

[ 1  2  3  4  5  6 -8] <class 'numpy.ndarray'>
2 1 [1 2 3 4]


In [17]:
# It can have higher dimentions:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.shape # 3 rows, 4 columns
# CAN NOT HAVE different sized COLUMN objects

print(a)
# lets call them axis, i.e.
# 3 length x axis, 4 length y axis

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# Array types
# Zero vector
a = np.zeros(3)
print("Zeros: ",a)
# Ones vector
a = np.ones(3)
print("Ones: ",a)
# Empty Vector: initial content is random and depends on the state of the memory
a = np.empty(3)
print("Empty: ",a)
# Range
a = np.arange(1,10,2) # same as range(from, to, step)
print("Arange: ",a)
# Linespace: Evenly spaced numbers
a = np.linspace(0, 10, num=5) # from, to, how many numbers
print("Linespace: ", a)
print("Linespace 2: ", np.linspace(1,15,num = 6))

Zeros:  [0. 0. 0.]
Ones:  [1. 1. 1.]
Empty:  [1. 1. 1.]
Arange:  [1 3 5 7 9]
Linespace:  [ 0.   2.5  5.   7.5 10. ]
Linespace 2:  [ 1.   3.8  6.6  9.4 12.2 15. ]


In [19]:
# Can specify data type
x = np.linspace(0,10,num = 50, dtype=np.int64)
print(x)

[ 0  0  0  0  0  1  1  1  1  1  2  2  2  2  2  3  3  3  3  3  4  4  4  4
  4  5  5  5  5  5  6  6  6  6  6  7  7  7  7  7  8  8  8  8  8  9  9  9
  9 10]


#### Sorting Arrays:

Can get as complex as needed, for now just regular sorts, it is interesting that it can change the orientation regardless of how the array elements are inputed.

In [20]:
arr = np.array([0,9,8,77])
print(np.sort(arr)) # This is a function to be applied to arr, not a method of itself

# Can take several dimentions of arrangemente
x = np.array([[0, 3,1,9], [2, 2,0,8]])

print("Axis = 0: \n",np.sort(x,axis = 0)) # sorts vertically
print("Axis = -1: \n",np.sort(x)) # default -1, horizontal
print("Argsort axis = 0: \n",np.argsort(x,axis = 0)) # Gimme the order of the arguments
print("Argsort axis = -1: \n",np.argsort(x)) # Gimme the order of the arguments

[ 0  8  9 77]
Axis = 0: 
 [[0 2 0 8]
 [2 3 1 9]]
Axis = -1: 
 [[0 1 3 9]
 [0 2 2 8]]
Argsort axis = 0: 
 [[0 1 1 1]
 [1 0 0 0]]
Argsort axis = -1: 
 [[0 2 1 3]
 [2 0 1 3]]


In [21]:
# Can join arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

c = np.concatenate((b,b,a*b,a)) # Takes tupple to concatenate it i.e. first argument must be ()

print(c)

# Reverses sorting: all the elements, beginning with the last element in reverse order
np.sort(c)[::-1]


[ 5  6  7  8  5  6  7  8  5 12 21 32  1  2  3  4]


array([32, 21, 12,  8,  8,  7,  7,  6,  6,  5,  5,  5,  4,  3,  2,  1])

In [22]:
# Can also add rows the same concatenate
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

print(np.concatenate((x,y)))

z = np.concatenate((x,x,x,y))

# Why tf are these two the same?

# Number of dimentions
print(z.ndim)
# print(np.ndim(z)) This also works

# Shape
print(z.shape) # elements per axis
# no arguments inside?
# Size
print(z.size) # Total number of elements



[[1 2]
 [3 4]
 [5 6]]
2
(7, 2)
14


In [23]:
# Three dimentional array example:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 6, 5, 7]],

                           [[0 ,1 ,8, 3],
                            [4, 5, 6, 7]]])

In [24]:
print(array_example)

np.sort(array_example) # Sorts by rows each matrix

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 6 5 7]]

 [[0 1 8 3]
  [4 5 6 7]]]


array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 3, 8],
        [4, 5, 6, 7]]])

# Why sometimes functions are called np.function(obj) and othertimes obj.function()

According to [this stackoverflow answer](https://stackoverflow.com/questions/66616456/why-do-i-only-need-the-name-of-the-module-in-front-of-module-functions-sometimes) it is bc when we create an object already defined inside a library then we can call functions to it bc it lives inside the library and therefore it does notneed to call the library:

In [25]:
# Testing that shit

test = np.linspace(1,10,num = 25)
print(np.sort(test))
print(test.sort())

[ 1.     1.375  1.75   2.125  2.5    2.875  3.25   3.625  4.     4.375
  4.75   5.125  5.5    5.875  6.25   6.625  7.     7.375  7.75   8.125
  8.5    8.875  9.25   9.625 10.   ]
None


Yeah not really, I'm not getting it all the way. But i see now that when I do `test.sort()` it returns `None` bc it is looking inside test fot the function sort, which is not there.  

In [26]:
a = np.arange(8)
b = a.reshape(4,2)
print(a,"\n",b)

[0 1 2 3 4 5 6 7] 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [27]:
np.reshape(b,newshape=(1,8)) # Reshape as a function, shape as a method for the thing

array([[0, 1, 2, 3, 4, 5, 6, 7]])

This seems important, [internal structure of arrays and reading orders](https://numpy.org/doc/stable/dev/internals.html#numpy-internals) but also looks impossible rn

In [28]:
# Reverse Ordering of things

print("Last ",a[-1])

Last  7


## Slicing arrays

In [29]:
# Array 1-d
a = np.linspace(1,99,num=9)
# array 2-d
a = a.reshape(3,3)
#
print(a,"\n")
# From index
print(a[0:3,1:3],"\n")# all rows, second to third column

# Condition to slice
print(a[a>10],"\n")

# Module: x%y == res (x divisible by y yields res)

print(a[a%5 == 0],"\n")



[[ 1.   13.25 25.5 ]
 [37.75 50.   62.25]
 [74.5  86.75 99.  ]] 

[[13.25 25.5 ]
 [50.   62.25]
 [86.75 99.  ]] 

[13.25 25.5  37.75 50.   62.25 74.5  86.75 99.  ] 

[50.] 



## And & Or | Operators
IMPORTANT

In [30]:
# ?np.random.randint 
# Can generate random integers in the form (low, high, size = (m,n,k)), default size = 1 
a = np.random.randint(1,100,size = 20)

# Conditions must be wraped in parennthesis:

print(a[(a >10) & (a<25)])

# Boolean of conditions
print("\n",(a >10) & (a<25))


# Same with or:

print("\n",a[(a%3 ==0) | (a<10)])

# Generally useful nonzero
# Nesting stuff! nice, also really quick

print("np.nonzero(condition)\nFirst array: Row where things that meet condition are found \nSecond array: Columns where values are found \n",np.nonzero(a.reshape(2,10)>90))


[13 14 16]

 [False False False  True False False False False False False  True False
 False False False  True False False False False]

 [57  4 33 39 75]
np.nonzero(condition)
First array: Row where things that meet condition are found 
Second array: Columns where values are found 
 (array([0, 1]), array([8, 3]))


In [31]:
# ZIP: paste (row[i], column[i])


b = np.nonzero(a>=63)
np.shape(b)

b = np.reshape(b,(2,4))

c = np.array([[212,22,18,4]])
# To concatenate things must be in the same dimention, always check,
# it is different [212,22,18,4] to [[212,22,18,4]]
d = np.concatenate((b,c))




### Note on 0 dimention and 1 dimention

In [32]:
print("np.array with onle 1 corchete: ",np.array([212,22,18,4] ).shape,"\n")
print("np. array with 2 corchetes: ",np.array([[212,22,18,4]]).shape,"\n")

np.array with onle 1 corchete:  (4,) 

np. array with 2 corchetes:  (1, 4) 



In [33]:
print(d)
# iterate over the list of coordinates, and print them
# Zip in two or three coordinates
print(list(zip(d[0],d[1],d[2])))# zip first axis w second w third
print(list(zip(d[0],d[1])))# zip first axis w second 

[[  1   2   8  13]
 [ 14  16  18  19]
 [212  22  18   4]]
[(1, 14, 212), (2, 16, 22), (8, 18, 18), (13, 19, 4)]
[(1, 14), (2, 16), (8, 18), (13, 19)]


In [34]:
# Stacking shit
a1 = np.array([[1, 1],
                [2, 2]])

a2 = np.array([[3, 3],
                [4, 4]])

In [35]:
# Note: Most python functions (that I've seen here) which take 2 arguments actualy only take one as tupple
print("Stacking two 2x2 vectors vertically:\n",np.vstack((a1,a2)))
print("Stacking two 2x2 vectors horizontally:\n",np.hstack((a1,a2)))
print("Concatenating two 2x2 vectors:\n",np.concatenate((a1,a2))) # Similar to vstack

Stacking two 2x2 vectors vertically:
 [[1 1]
 [2 2]
 [3 3]
 [4 4]]
Stacking two 2x2 vectors horizontally:
 [[1 1 3 3]
 [2 2 4 4]]
Concatenating two 2x2 vectors:
 [[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [36]:
x = np.arange(1, 25).reshape(2, 12)

# Split array into equal parts
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [37]:
# What the fuck
# First three columns, then fourth, then everything else
np.hsplit(x, (3, 4))

# First four, then 5,6 then everything else
np.hsplit(x, (4, 6))

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [38]:
# Splitting and substituting shit
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b1 = a[1,:]

b1[0]

5

In [39]:
# Change that specific indexed value
b1[0] = 99

In [40]:
b1

array([99,  6,  7,  8])

In [41]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [42]:
y = np.hsplit(x, (4, 6)) # View, shallow copy of the thing
y[0]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [43]:
y[0] = 1000

In [44]:
y

[1000,
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [45]:
y = x.copy() # Deep copy (some shit idk)
y

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

Holy shit, ChatGPT literally explained that shit to me:

Shallow copies only copy the reference pointers to the original data, but not the data itself.



In [46]:
import copy

# Original list
original_list = [1, [2, 3], 4]

# Shallow copy
shallow_copy = copy.copy(original_list)

# Deep copy
deep_copy = copy.deepcopy(original_list)

# Modify the nested list in the original list
original_list[1][0] = 'a'

# Verify changes
print(original_list)  # Output: [1, ['a', 3], 4]
print(shallow_copy)   # Output: [1, ['a', 3], 4]
print(deep_copy)      # Output: [1, [2, 3], 4]


[1, ['a', 3], 4]
[1, ['a', 3], 4]
[1, [2, 3], 4]


### Chat GPT explanation to methods vs. standalone functions:
The difference between these two types of functions is that a method is associated with a specific object and operates on the data contained in that object, while a standalone function can operate on any object or data that is passed to it.


* Methods: Object specific
* Functions: work on anything


For example, consider the built-in function len(), which is a standalone function. It can operate on any object that has a length, such as a list or a string. You call it using the syntax len(object).

On the other hand, consider the string method upper(), which is a method of the string object. It operates on the data contained in the string object and returns a modified string. You call it using the syntax string.upper().

In [47]:
my_list = [1, 2, 3, 4, 5]

# Call the len() function on my_list
length = len(my_list)

# Call the append() method on my_list
my_list.append(6)

print(length)   # Output: 5
print(my_list)  # Output: [1, 2, 3, 4, 5, 6]


5
[1, 2, 3, 4, 5, 6]


### Regular Ops:

In [48]:
x = np.random.randint(1,66,size = 10)
y = np.array(np.random.randint(1,100,size = (10,1)))
x = np.array(x)
x.size
x.ndim
x = x[np.newaxis,:]

x.ndim
x.shape
y.shape

(10, 1)

In [49]:
print("Line * Column: Recular Vector multiplication\n",x*y)

print("Line * Line: Works as dot product\n",y.transpose() * x)

print("Col * Col: Works as dot product\n",y * x.transpose())


Line * Column: Recular Vector multiplication
 [[2366 3913 5460 4368 2093 4732 3185 3185 5005 2730]
 [ 832 1376 1920 1536  736 1664 1120 1120 1760  960]
 [1872 3096 4320 3456 1656 3744 2520 2520 3960 2160]
 [ 728 1204 1680 1344  644 1456  980  980 1540  840]
 [1066 1763 2460 1968  943 2132 1435 1435 2255 1230]
 [ 780 1290 1800 1440  690 1560 1050 1050 1650  900]
 [ 962 1591 2220 1776  851 1924 1295 1295 2035 1110]
 [ 598  989 1380 1104  529 1196  805  805 1265  690]
 [2314 3827 5340 4272 2047 4628 3115 3115 4895 2670]
 [1534 2537 3540 2832 1357 3068 2065 2065 3245 1770]]
Line * Line: Works as dot product
 [[2366 1376 4320 1344  943 1560 1295  805 4895 1770]]
Col * Col: Works as dot product
 [[2366]
 [1376]
 [4320]
 [1344]
 [ 943]
 [1560]
 [1295]
 [ 805]
 [4895]
 [1770]]


In [50]:
z = y.transpose()

r = np.concatenate((x,z)).transpose()

r.shape
# Just fucking around
list(zip(x.transpose(),y))


[(array([26]), array([91])),
 (array([43]), array([32])),
 (array([60]), array([72])),
 (array([48]), array([28])),
 (array([23]), array([41])),
 (array([52]), array([30])),
 (array([35]), array([37])),
 (array([35]), array([23])),
 (array([55]), array([89])),
 (array([30]), array([59]))]

    Operations are regular product operations:

In [51]:
x + z

array([[117,  75, 132,  76,  64,  82,  72,  58, 144,  89]])

In [52]:
z - x

array([[ 65, -11,  12, -20,  18, -22,   2, -12,  34,  29]])

In [53]:
z / x

array([[3.5       , 0.74418605, 1.2       , 0.58333333, 1.7826087 ,
        0.57692308, 1.05714286, 0.65714286, 1.61818182, 1.96666667]])

In [54]:
z * x

array([[2366, 1376, 4320, 1344,  943, 1560, 1295,  805, 4895, 1770]])

In [55]:
test_m = y*x

print(test_m)

print("Adding along x axis:\n",test_m.sum(axis = -1))
print("Adding along y axis:\n",test_m.sum(axis = 0))

[[2366 3913 5460 4368 2093 4732 3185 3185 5005 2730]
 [ 832 1376 1920 1536  736 1664 1120 1120 1760  960]
 [1872 3096 4320 3456 1656 3744 2520 2520 3960 2160]
 [ 728 1204 1680 1344  644 1456  980  980 1540  840]
 [1066 1763 2460 1968  943 2132 1435 1435 2255 1230]
 [ 780 1290 1800 1440  690 1560 1050 1050 1650  900]
 [ 962 1591 2220 1776  851 1924 1295 1295 2035 1110]
 [ 598  989 1380 1104  529 1196  805  805 1265  690]
 [2314 3827 5340 4272 2047 4628 3115 3115 4895 2670]
 [1534 2537 3540 2832 1357 3068 2065 2065 3245 1770]]
Adding along x axis:
 [37037 13024 29304 11396 16687 12210 15059  9361 36223 24013]
Adding along y axis:
 [13052 21586 30120 24096 11546 26104 17570 17570 27610 15060]


In [56]:
# "Brodcasting": Array multiplication between different size arrays

test_m*1.5



array([[3549. , 5869.5, 8190. , 6552. , 3139.5, 7098. , 4777.5, 4777.5,
        7507.5, 4095. ],
       [1248. , 2064. , 2880. , 2304. , 1104. , 2496. , 1680. , 1680. ,
        2640. , 1440. ],
       [2808. , 4644. , 6480. , 5184. , 2484. , 5616. , 3780. , 3780. ,
        5940. , 3240. ],
       [1092. , 1806. , 2520. , 2016. ,  966. , 2184. , 1470. , 1470. ,
        2310. , 1260. ],
       [1599. , 2644.5, 3690. , 2952. , 1414.5, 3198. , 2152.5, 2152.5,
        3382.5, 1845. ],
       [1170. , 1935. , 2700. , 2160. , 1035. , 2340. , 1575. , 1575. ,
        2475. , 1350. ],
       [1443. , 2386.5, 3330. , 2664. , 1276.5, 2886. , 1942.5, 1942.5,
        3052.5, 1665. ],
       [ 897. , 1483.5, 2070. , 1656. ,  793.5, 1794. , 1207.5, 1207.5,
        1897.5, 1035. ],
       [3471. , 5740.5, 8010. , 6408. , 3070.5, 6942. , 4672.5, 4672.5,
        7342.5, 4005. ],
       [2301. , 3805.5, 5310. , 4248. , 2035.5, 4602. , 3097.5, 3097.5,
        4867.5, 2655. ]])

In [57]:
test_m.min()

529

In [58]:
test_m.max()

5460

In [59]:
# Can always specify axis

test_m.min(axis = 0)

array([ 598,  989, 1380, 1104,  529, 1196,  805,  805, 1265,  690])

### Matrices

2-D arrays, we knew that but yea

In [62]:
mat = np.array(([1,3],[3,4],[9,8]))
mat

array([[1, 3],
       [3, 4],
       [9, 8]])

In [66]:
# Commands which work on tibbles and dfs in R do work but in arrays, 
# for data frames and stuff i feel it's a little different

print("Element: ", mat[1,1])
print("Col: ",mat[0:2,1])
print("Row: ",mat[2,:])
# Does not distinguish graphically vectors

Element:  4
Col:  [3 4]
Row:  [9 8]


In [67]:
# Operating in matrixes is kinda weird, multiplying or adding vectors
# Does the same for every entry
vec = np.array(([2,2]))

mat * vec

array([[ 2,  6],
       [ 6,  8],
       [18, 16]])

In [71]:
mat_2 = np.ones((3,2))*2

In [73]:
# Yields same result
mat * mat_2

array([[ 2.,  6.],
       [ 6.,  8.],
       [18., 16.]])

In [74]:
# Same with other ops:

mat - mat_2 == mat - vec


array([[ True,  True],
       [ True,  True],
       [ True,  True]])